modified to program and application (#4)
ubc/hotcrp pull request #5
Opened 2024-03-04 21:12 UTC by ubc-tuehoang

* update conference to program

* updated paper to application

* modified paper to application for json files

* updated message

* updated help log for paper

* updated more help content fixes

---------

2024-03-04 21:48 UTC, xcompass requested changes
I also remember you said you are going to make variables for changing those texts. Did you give it up?

2024-03-04 21:48 UTC, xcompass commented on .env.default
> -
Could you remove this change? I would like minimal changes for the PR. Will be easier for merging in the future.

2024-03-04 21:48 UTC, xcompass commented on src/help/h_chairsguide.php
> +  "</strong> Tracks give chairs fine-grained control over PC members’ access rights for individual papers. Example situations calling for tracks include external review committees, PC-paper review co
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/help/h_chairsguide.php
> +        echo "<p>Chairs and system administrators can access any information stored in the program system, including reviewer identities for conflicted papers. It is easiest to simply accept such con
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/help/h_chairsguide.php
> +“Override conflicts” to access the assignment page.) Paper administrators have full privilege to assign and view reviews for their papers, and can, for example, use the autoassignment tool, but they
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/help/h_chairsguide.php
> +            echo "<li><p><strong>Shepherding (optional).</strong> If your program uses shepherding for accepted applications, you can assign shepherds either ",
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/help/h_developer.php
>      $this->hth->hotlink("JSON format", "help", ["t" => "jsonsettings"]) . ".
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/help/h_developer.php
> +        echo "<p>The <code>api/paper</code> endpoint accesses program submissions. GET calls return paper information; use
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/help/h_jsonsettings.php
> +            ", administrators can configure site operation by modifying a JSON specification. Advanced users can copy settings from one program to another and configure aspects of the site not access
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/help/h_jsonsettings.php
> +<li><p><strong>Copying settings between programs.</strong> Beware of IDs
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/help/h_tags.php
> +        echo "<p>PC members and administrators can attach tag names to applicaitons. It’s easy to change tags and to list all applications with a given tag, and <em>ordered</em> tags preserve a parti
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/help/h_tags.php
> +<p>You can also search with “", $hth->search_link("show:tags"), "” to see each application’s tags, or “", $hth->search_link("show:#tagname"), "” to see a particular tag
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/pages/p_home.php
> +        echo '<div id="motivationalQuotes">
what about this change?

2024-03-04 21:48 UTC, xcompass commented on src/pages/p_mergeaccounts.php
> +            'You may have multiple accounts registered; perhaps you were asked to review applications using different email addresses. This form will allow you to transfer information between account
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-04 21:48 UTC, xcompass commented on src/userstatus.php
> +        echo '<p>Please indicate your interest in reviewing applications on these program topics. We use this information to help match papers to reviewers.</p>',
Could you not change the line breaks but just the text? again easier for future merge.

2024-03-05 00:22 UTC, ubc-tuehoang commented on src/pages/p_home.php
> +        echo '<div id="motivationalQuotes">
It was for fun - I will remove it.  😀

2024-03-22 17:52 UTC, xcompass requested changes

2024-03-22 17:52 UTC, xcompass commented on src/userstatus.php
> +        echo '<p>Please indicate your interest in reviewing applications on these program topics. We use this information to help match papers to reviewers.</p>',
Just a reminder to change this.

2024-03-22 17:52 UTC, xcompass commented on src/help/h_chairsguide.php
> +            echo "<li><p>Consider checking ", $hth->search_link("the apps", ["q" => "", "t" => "all"]),
Could you change all `app` and `apps` to `application` and `applications`? The wording apps may confuse applicants.

2024-03-22 17:52 UTC, xcompass commented
Thanks for the update. Almost there.

2024-03-26 21:06 UTC, xcompass commented
Looks like some of the text in the tests are not updated causing the tests failing. Could you check? @tuehoang

2024-03-27 21:30 UTC, merged